### ISSUE TITLE
Don't load tabs if browser.sessionstore.restore_pinned_tabs_on_demand not setted 

### ISSUE THREAD

**Issue by mariushartig** [Faerbit/persistentpin-webextension#10]
as a user i don't want load always all tabs. if i set in the config the flag browser.sessionstore.restore_pinned_tabs_on_demand to false normally firefox don't load the tabs but the extension don't core about this.

**Comment by Faerbit** [comment]
I'm not sure this is even possible. See [here](https://discourse.mozilla.org/t/setting-browser-preferences-when-using-webextensions-api/8561).
