### ISSUE TITLE
Pinned tab gone on restart

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Faerbit/persistentpin-webextension#14]
Unfortunately, the AddOn appears not to work.

I went to [this page](https://addons.mozilla.org/en-US/firefox/addon/persistentpin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) (the page within the Mozzila addOn webpages for the addOn), installed the AddOn, pinned the current page, restarted and the page was no pinned. Restarting Firefox, revisiting the page, pinning it, and restarting once more gave the same result, i.e. no pin. EDIT: and I tried pinning this github page, and I got the same (lack of) result.

Windows 10
Firefox 82.0.2 x64
PersistentPin 1.0.2

**Comment by Faerbit** [comment]
This addon will not automatically restore all pinned addons. You need to configure which tabs should be persisted. Use the provided menu for that (click "Options" after selecting the addon in the Add-ons Manager).

**Comment by LinuxOnTheDesktop** [comment]
Ah. Thanks.

Given that to restore an arbitrary tab - one not specified in advance - one must use the 'grab current pinned tabs' option, it would make the addOn more usable were one able to activate that function via an icon next to the URL bar.
