### ISSUE TITLE
Instructions seem needed but missing

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Faerbit/persistentpin-webextension#15]
Thank you for your AddOn.

I could find no instructions. I thought perhaps one is meant to work out how to use the addOn via the link to App Tab Initializer. Yet, that link is broken.

**Comment by Faerbit** [comment]
If you go to your addon page, click on this addon, there should be an "Options" tab. There you can do the configuration. This is the same for all addons. But it could be you have never seen this, since many of them insist on adding some kind of icon to your menu bar.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I should have said that I had seen that material. Thus, I see this:

![image](https://user-images.githubusercontent.com/47056543/118859153-d075f880-b8d1-11eb-9f4d-23a0d8757eac.png)

I suppose that my point is twofold. (1) That sight is not self-explanatory although, admittedly, it comes close to being so. (2) The user is not really directed in any way to that sight. 1 and 2 combine to make the user feel somewhat at a loss. You might want to try somehow to prevent that feeling.

**Comment by Faerbit** [comment]
I added an additional sentence to the add-on page to direct the user to this page, if they don't find it themselves. I designed the UI like this, because this is the best I could come up with. Do you have any suggestions on how to improve it?

>That sight is not self-explanatory although

Since I have come up with it, I have no insight as to what might be difficult to grasp. I would need more details to be able to improve on it.

**Comment by LinuxOnTheDesktop** [comment]
> I added an additional sentence to the add-on page to direct the user to this page,

Jolly good. Thanks.

> I would need more details [. . .]

Can you add text to (or below), 'Pins the same websites across browser restarts'? If so, consider adding something like the following.

> Use the 'Options' tab below to add, edit and reorder pinned URLs. You can populate the list of URLs using the 'grab' button.

Also, consider making the 'grab' button looking less like a drop-down menu.

**Comment by Faerbit** [comment]
>If so, consider adding something like the following.

Nah, that's a little too much imo. I can see how it might  be possible to miss that the options tabs exists at all. But I don't want to put any text, which just explains, what should be clear from the button captions.

>Also, consider making the 'grab' button looking less like a drop-down menu.

This looks much better for me compared to your screenshot. This is OS dependent afaik. However I centered the text. Does that help?

**Comment by LinuxOnTheDesktop** [comment]
I updated the AddOn and now, on Windows, I see this:

![image](https://user-images.githubusercontent.com/47056543/119037602-19997b80-b9aa-11eb-9a7b-f9dc77b2277a.png)

But on Linux (where I had not tested the addOn before) I see the following, which is fine:

![image](https://user-images.githubusercontent.com/47056543/119038012-8f9de280-b9aa-11eb-889b-2927aa505c9e.png)
