### ISSUE TITLE
Pins doubled on restart

### ISSUE THREAD

**Issue by vwbusguy** [Faerbit/persistentpin-webextension#3]
If Firefox is closed with pinned tabs that match the pins saved in the extension, the pins are opened twice in the next Firefox session.  

The workaround seems to be to open a new, empty window, close the one with tabs, then close the new window - then only the saved tabs will persist.

![screenshot from 2017-12-06 09-34-27](https://user-images.githubusercontent.com/5474941/33675854-ddbeeede-da68-11e7-9649-40bfe4e088b3.png)

**Comment by Faerbit** [comment]
Do you have the setting 'Clear history when Firefox closes' enabled?
I have created this addon, because there Firefox does not save my pinned tabs when I clear my history on exit.
Otherwise Firefox does a fine job of remembering the pinned tabs on it own.
I guess I am unsure of you're usecase.

**Comment by robinsonaaron** [comment]
My issue is that sometimes Firefox loses its session information so the pinned tabs aren't saved. However, I don't want to delete my history.

**Comment by Faerbit** [comment]
Should be solved with #4.
