### ISSUE TITLE
Grab current pinned tabs from browser button or context menu item.

### ISSUE THREAD

**Issue by wellread1** [Faerbit/persistentpin-webextension#8]
I am enjoying using your Persistent Pin extension.  I use it in two ways (1) To pin sites I visit often (2) To pin sites that I am currently working on.  The latter type of pinned tab needs to change fairly regularly.  

I would find it useful to have an easy way (perhaps a button, or a context menu item) to "grab current pinned tabs".

**Comment by GabhanOLoughlin** [comment]
Agreed - one of my favourite Firefox add-ons. And an easier way to 'Grab Pinned Tabs' would be the icing on the cherry on the cake!

**Comment by wellread1** [comment]
Thank-you for implementing this feature.  I am sure it will be very useful when I am working on a project.   However, I have just tested it and I find it does not seem to update the PersistantPin's Website list.  I tested on two computers as follows:

Firefox 88.0.1 (64 bit) - New, clean profile with PersistantPin as the only Extension
Windows 10 ver 20H2 build 19042.985
PersistantPin ver 1.04 - Default settings with 'Add "Grab currently pinned tabs" to tab context menu enabled
Pinned website: https://github.com/Faerbit/persistentpin-webextension

Result:  The "Grab currently pinned tabs" option is available on the context menu but selecting it does not add the pinned website to the PersistantPin's Website list.  Restarting Firefox causes the pinned website to be briefly appear but it quickly disappears.  I believe this is expected behavior because Firefox remembers the pinned sites before PersistantPin overrides Firefox.

To eliminate the possibility that another application was causing interference.  I repeated the test on one computer in Window safe-mode with the same result.

**Comment by Faerbit** [comment]
I wasn't able to trigger an UI update after you used the menu item in the tab context menu. However if you exit the options screen (just click the back arrow) and open it back up again, the list should reflect the currently pinned websites.

> Restarting Firefox causes the pinned website to briefly appear but it quickly disappears.

So you're saying, the context menu item, doesn't make the pin persistent? Because that was the whole point, and I tested that this works. If it doesn't work for you, I can try to take a look at it again, to see if I have missed something.

>To eliminate the possibility that another application was causing interference. I repeated the test on one computer in Window safe-mode with the same result.

Thank you for taking the time to rule out outside interference.

**Comment by Faerbit** [comment]
Took another stab at it. Should work now. Also implemented an live update of the preference page. Do let me know if it works for you now.

**Comment by wellread1** [comment]
Beautiful, works like a charm. Thanks!

Just a heads up:  I like the way that when multiple Firefox windows are open it is possible to add a pinned tab to the Website list from the secondary Firefox window.  However, I noticed in at least one instance I created a duplicate pinned tab.  I need to live with the extension for a while before reporting more.

**Comment by GabhanOLoughlin** [comment]
Super work - I'll also give it some testing over the next few days, as I'm setting up a new laptop which I'll be syncing with my desktop. I'm always updating my persistent pins so if this all works it'll be superb!!

**Comment by GabhanOLoughlin** [comment]
> 
> 
> Super work - I'll also give it some testing over the next few days, as I'm setting up a new laptop which I'll be syncing with my desktop. I'm always updating my persistent pins so if this all works it'll be superb!!

Been updating my pinned tabs daily using the context menu and all seems to be working for me. Thanks so much @Faerbit

**Comment by wellread1** [comment]
After using this for 10 days I find being able to pin tabs from the context menu really useful.  The addition of cross device syncing is also another excellent improvement.  Thanks again.
