### ISSUE TITLE
This only works for the first Firefox Window opened. 

### ISSUE THREAD

**Issue by CPISolutionsAV** [Faerbit/persistentpin-webextension#9]
Is this normal? Can it be configured to work on any new window opened? I would love to be able to have my quad browser windows all open with the tabs I want pinned.

Jamie

**Comment by Faerbit** [comment]
Yes, this is normal.
No, it can currently not be configured to work this way.
I would not be averse to a PR, which adds this functionality.
If you want a quick hack, just disable [this](https://github.com/Faerbit/persistentpin-webextension/blob/012a2d3a59dbfdc37c765db6e8057c42aa54ccf9/src/background.js#L25) check. Obviously you would need to build the addon yourself.

**Comment by CPISolutionsAV** [comment]
Thanks for the quick response. Unfortunatly doing this myself is a bit over my head! Im not even sure what a PR is. HEHE.

**Comment by Sharsie** [comment]
I actually took a shot at this, however it was not as simple as disabling the check as the JS is executed only once.
It required a rewrite of the openinig logic, I don't really want this functionality, but I wanted to dig a bit around web-ext and this seemed like a good way to start :)
So I thought I would share it, will submit a PR momentarily, but feel free to disregard it if you feel it's not worthwhile or don't like the changes @Faerbit .

**Comment by Faerbit** [comment]
New version is live now :tada:
